export const typeOfArtwork = [
    { name: 'Digital Art'},
    { name: 'Traditional Art'},
    { name: 'Photography' },
    { name: 'Graphic Design' },
    { name: 'UI/UX Design'},
    { name: '3D Art'},
    { name: 'VFX' },
    { name: 'Motion Graphics' },
    { name: 'Mixed Media' },
    { name: 'Game Design' },
    { name: 'Animation' },

   
    
]

export const softwareUsed = [
    { name: 'Adobe After Effects' },
    { name: 'Adobe Animate' },
    { name: 'Adobe Illustrator'},
    { name: 'Adobe Photoshop'},
    { name: 'Adobe Premiere Pro' },
    { name: 'Affinity Designer' },
    { name: 'Affinity Photo' },
    { name: 'ArtRage' },
    { name: 'Artweaver' },
    { name: 'Autodesk SketchBook' },
    { name: 'Black Ink' },
    { name: 'Blender'},
    { name: 'Cinema 4D' },
    { name: 'Clip Studio Paint' },
    { name: 'CorelDRAW' },
    { name: 'CrazyTalk Animator' },
    { name: 'DaVinci Resolve' },
    { name: 'DragonBones' },
    { name: 'FireAlpaca' },
    { name: 'Fusion' },
    { name: 'GIMP' },
    { name: 'Houdini' },
    { name: 'Inkscape' },
    { name: 'Krita' },
    { name: 'Maya'},
    { name: 'MediBang Paint' },
    { name: 'Mischief' },
    { name: 'Moho' },
    { name: 'MyPaint' },
    { name: 'Nuke' },
    { name: 'OpenCanvas' },
    { name: 'OpenToonz' },
    { name: 'Paint Tool SAI' },
    { name: 'Paint.NET' },
    { name: 'Photopea' },
    { name: 'Pixlr' },
    { name: 'Procreate' },
    { name: 'Project Dogwaffle' },
    { name: 'Rebelle' },
    { name: 'Spine' },
    { name: 'Substance Painter' },
    { name: 'Toon Boom Harmony' },
    { name: 'Tupi' },
    { name: 'TwistedBrush' },
    { name: 'Unity' },
    { name: 'Unreal Engine' },
    { name: 'ZBrush' },
];
